CREATE TABLE tours (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    category_id INT,
    operator_id INT,
    start_date DATE,
    end_date DATE,
    status NVARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'passive', 'cancelled')),
    show_on_homepage BIT DEFAULT 0,
    price_double DECIMAL(10,2),
    price_single DECIMAL(10,2),
    price_triple DECIMAL(10,2),
    price_child1 DECIMAL(10,2),
    price_child2 DECIMAL(10,2),
    theme_id INT,
    region_id INT,
    country_id INT,
    city_id INT,
    guide_id INT,
    notes NVARCHAR(MAX),
    contract NVARCHAR(MAX),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (operator_id) REFERENCES operators(id),
    FOREIGN KEY (theme_id) REFERENCES themes(id),
    FOREIGN KEY (region_id) REFERENCES regions(id),
    FOREIGN KEY (country_id) REFERENCES countries(id),
    FOREIGN KEY (city_id) REFERENCES cities(id),
    FOREIGN KEY (guide_id) REFERENCES guides(id)
);